/* Header for class cn_rexih_android_testkotlinlinuxthread_jni_CountJni */
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <android/log.h>
#include <pthread.h>
#include <sstream>
#include <map>
#ifndef _Included_cn_rexih_android_testkotlinlinuxthread_jni_CountJni
#define _Included_cn_rexih_android_testkotlinlinuxthread_jni_CountJni
extern "C" {
#endif

/*
 * Class:     cn_rexih_android_testkotlinlinuxthread_jni_CountJni
 * Method:    setCallback
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_cn_rexih_android_testkotlinlinuxthread_jni_CountJni_setCallback
(JNIEnv *, jobject, jobject);

/*
 * Class:     cn_rexih_android_testkotlinlinuxthread_jni_CountJni
 * Method:    createTask
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_rexih_android_testkotlinlinuxthread_jni_CountJni_createTask
(JNIEnv *, jobject, jstring);

/*
 * Class:     cn_rexih_android_testkotlinlinuxthread_jni_CountJni
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_rexih_android_testkotlinlinuxthread_jni_CountJni_destroy
(JNIEnv *, jobject);

void JNICALL notifyCallback(JNIEnv *env, const char *threadName, int count, int type);

void JNICALL releaseGlobalCache(JNIEnv *env);
#ifdef __cplusplus
}
#ifdef __cplusplus
#endif

#endif
